### ISSUE TITLE
LiteLoader Version

### ISSUE THREAD

**Issue by Sascha-T** [kukiteam/kuki-mpf#2]
Define please? Please provide examples too.

**Comment by Anoobarmy** [comment]
No idea what this is but, Cool!

**Comment by Anoobarmy** [comment]
no u

**Comment by NobodyMiner** [comment]
The easiest way to get a liteloader version is currently by using their [repository manifest](http://dl.liteloader.com/versions/versions.json). This currently shows my [these versions](https://i.imgur.com/7noepfZ.png) which are all game versions. We could switch to a boolean to indicate to use the same version as the game version (would kindof break snapshots) or we could use a string to use for game versions
@Sascha-T

**Comment by Sascha-T** [comment]
I am no expert with their repository manifest.
It kind of confuses me a little.
![ok then](https://user-images.githubusercontent.com/16324266/49892093-67f4d880-fe48-11e8-9e15-9f6183fe653f.png)
I'd say you choose which one you think is better, I'll probably get it working either way.

**Comment by NobodyMiner** [comment]
We'll just make it a boolean and use the same version as is used for the minecraft version, they don't support snapshots, so this won't break anything

**Comment by NobodyMiner** [comment]
Fixed in 9d408a2ba206ce663d496139243ecedc6ce3ece5
