### ISSUE TITLE
Suggestion: Add multiple hash types back

### ISSUE THREAD

**Issue by Sascha-T** [kukiteam/kuki-mpf#4]
Well, my code isn't very compliant with the standard anymore due to you removing support for using sha512.
I request you add the other types back again.

**Comment by NobodyMiner** [comment]
We could do that but Minecraft and Forge both only use sha1 so I thought it would be better that way... We could support the others if you want...

**Comment by Sascha-T** [comment]
id prefer using sha512 imho

**Comment by NobodyMiner** [comment]
Fixed in 34456ddb7f8d8b31cfdb5ab492095a388b75d4e3
